# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA
#' @title Sample nSim MC samples from a SUN with time constant terms using Rcpp and Armadillo.
#' @description Function Sample nSim MC samples from a SUN with time constant terms using Rcpp and Armadillo.
#' @param y Binary vector of 1,0 or NA 
#' @param delta Vector for time constant covariates.
#' @param gamma Vector for time varying covariates. 
#' @param x Vector encoding time constant covariates.
#' @param Z Matrix encoding time varing covariates, columns are observed times.
#' @param matFF Encoding of evolutions coefficents.
#' @param G Evolution matrix.
#' @param mu0 Prior mean for starting time.
#' @param Sigma0 Prior variance for starting time.
#' @param SigmaEps Evolution prior.
#' @param nSim Number of samples.
#' @param seed seed to be fixed.
#' @return Random samples of evoution coefficents.
#' @examples 1+1 == 2
#' @field conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA Rcpp Function.
#' @field RaoBlackwellAuxSMC_witcovs_andNA Original R function.
NULL

#' @name mvrnormArma
#' @title Samples from mutivariate normal using Rcpp and Armadillo
#' @description Function to return 1 or n samples from a mutivariate normal using Rcpp and Armadillo
#' @param n number of samples .
#' @param mu Mean vector.
#' @param sigma Covariance matrix vector.
#' @return Random samples
#' @examples mvrnormArma(n = 1, mu = c(0,0), sigma = diag(c(1,1)))
#' @field mvrnormArma Return n sample from a mutivariate normal.
#' @field mvrnormArma1 Return a sample from a mutivariate normal.
mvrnormArma <- function(n, mu, sigma) {
    .Call(`_HEP_mvrnormArma`, n, mu, sigma)
}

#' @rdname mvrnormArma
mvrnormArma1 <- function(mu, sigma) {
    .Call(`_HEP_mvrnormArma1`, mu, sigma)
}

rcpp_sample <- function(vec, size, prob) {
    .Call(`_HEP_rcpp_sample`, vec, size, prob)
}

conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA <- function(y, delta, gamma, x, Z, matFF, G, mu0, Sigma0, SigmaEps, nSim = 100L, seed = 1L) {
    .Call(`_HEP_conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA`, y, delta, gamma, x, Z, matFF, G, mu0, Sigma0, SigmaEps, nSim, seed)
}

