# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name mvrnormArma
#' @title Samples from mutivariate normal using Rcpp and Armadillo
#' @description Function to return 1 or n samples from a mutivariate normal using Rcpp and Armadillo
#' @param n number of samples .
#' @param mu Mean vector.
#' @param sigma Covariance matrix vector.
#' @return Random samples
#' @examples mvrnormArma(n = 1, mu = c(0,0), sigma = diag(c(1,1)))
#' @field mvrnormArma Return n sample from a mutivariate normal.
#' @field mvrnormArma1 Return a sample from a mutivariate normal.
NULL

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_HEP_mvrnormArma`, n, mu, sigma)
}

#' @rdname mvrnormArma
mvrnormArma1 <- function(mu, sigma) {
    .Call(`_HEP_mvrnormArma1`, mu, sigma)
}

conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA <- function(y, delta, gamma, x, Z, matFF, G, mu0, Sigma0, SigmaEps, nSim = 100L, seed = 1L) {
    .Call(`_HEP_conditioned_C_RaoBlackwellAuxSMC_witcovs_andNA`, y, delta, gamma, x, Z, matFF, G, mu0, Sigma0, SigmaEps, nSim, seed)
}

